# ruff: noqa: F401
# flake8: noqa: F401
"""Target-neutral styled text."""
from .builders import StyledTextBuilder
from .colors import Color
from .colors import RgbColor
from .colors import parse_rgb
from .styles import DEFAULT_COLOR
from .styles import EMPTY_STYLE_PATCH
from .styles import EMPTY_STYLE_THEME
from .styles import PLAIN_STYLE
from .styles import ColorDefault
from .styles import ResolvedStyle
from .styles import StyleColor
from .styles import StyleLike
from .styles import StyleName
from .styles import StyleNameLike
from .styles import StylePatch
from .styles import StyleRef
from .styles import StyleTheme
from .styles import as_style_ref
from .texts import ResolvedStyledTextRun
from .texts import StyledText
from .texts import StyledTextLike
from .texts import StyledTextRun
from .texts import StyleSpan
