import typing as ta

from .... import dataclasses as dc
from .... import typedvalues as tv
from ...dtypes import Boolean
from ...dtypes import Bytes
from ...dtypes import Datetime
from ...dtypes import Float
from ...dtypes import Integer
from ...dtypes import String
from ...dtypes import Uuid
from ...qualifiedname import QualifiedName
from ...tabledefs.diffing import AlterColumn
from ...tabledefs.elements import Column
from ...tabledefs.elements import Index
from ...tabledefs.elements import UpdatedAtTrigger
from ...tabledefs.elements import index_name
from ...tabledefs.options import Clustered
from ...tabledefs.rendering import Renderer
from ...tabledefs.tabledefs import TableDef
from ...tabledefs.triggers import TriggerRenderer


##


CREATE_UPDATED_AT_TRIGGER_FUNCTION_SRC = """\
create or replace function {function_name}()
returns trigger
language plpgsql
as $$
begin
  if new.{column_name} is not distinct from old.{column_name} then
    new.{column_name} := current_timestamp;
  end if;

  return new;
end;
$$\
"""


CREATE_UPDATED_AT_TRIGGER_SRC = """\
create {or_replace}trigger {trigger_name}
before update on {table_name}
for each row
execute function {function_name}()
"""


class PostgresUpdatedAtTriggerRenderer(TriggerRenderer[UpdatedAtTrigger]):
    @property
    def trigger_cls(self) -> type[UpdatedAtTrigger]:
        return UpdatedAtTrigger

    @classmethod
    def function_name(cls, trigger_name: str) -> str:
        # The trigger function is a separate, schema-level object. Naming it by a fixed rewrite of the trigger's own
        # name lets a drop - which knows only the trigger name - find it again.
        return trigger_name.replace('__trigger__', '__function__', 1)

    def create_statements(
            self,
            r: Renderer,
            tbl: TableDef,
            t: UpdatedAtTrigger,
            opts: Renderer.CreateOptions,
    ) -> list[str]:
        trigger_name = t.trigger_name(tbl.name)
        function_qn = tbl.name.sibling(self.function_name(trigger_name))

        return [
            CREATE_UPDATED_AT_TRIGGER_FUNCTION_SRC.format(
                function_name=r.qname(function_qn),
                column_name=r.quote_ident(t.column),
            ),
            CREATE_UPDATED_AT_TRIGGER_SRC.format(
                # Postgres 14+ has 'create or replace trigger', which stands in for the missing 'if not exists'.
                or_replace='or replace ' if opts.if_not_exists else '',
                trigger_name=r.quote_ident(trigger_name),
                table_name=r.qname(tbl.name),
                function_name=r.qname(function_qn),
            ),
        ]

    def drop_statements(
            self,
            r: Renderer,
            table_name: QualifiedName,
            name: str,
    ) -> list[str]:
        function_qn = table_name.sibling(self.function_name(name))

        return [
            f'drop trigger if exists {r.quote_ident(name)} on {r.qname(table_name)}',
            f'drop function if exists {r.qname(function_qn)}()',
        ]


##


POSTGRES_INTEGER_TYPES_BY_BITS: ta.Mapping[int, str] = {
    16: 'smallint',
    32: 'integer',
    64: 'bigint',
}


class PostgresTabledefRenderer(Renderer):
    max_ident_length = 63

    def builtin_trigger_renderers(self) -> ta.Sequence[TriggerRenderer]:
        return [PostgresUpdatedAtTriggerRenderer()]

    def column_type(self, c: Column, *, is_identity: bool, indexed: bool = False) -> str:
        if isinstance(c.type, String):
            return f'varchar({c.type.length})' if c.type.length is not None else 'text'
        elif isinstance(c.type, Uuid):
            return 'uuid'
        elif isinstance(c.type, Integer):
            return POSTGRES_INTEGER_TYPES_BY_BITS[self.integer_bits(c.type, is_identity=is_identity)]
        elif isinstance(c.type, Datetime):
            return 'timestamp with time zone'
        elif isinstance(c.type, Boolean):
            return 'boolean'
        elif isinstance(c.type, Float):
            return 'double precision'
        elif isinstance(c.type, Bytes):
            return 'bytea'
        else:
            raise TypeError(c.type)

    def column_identity_sql(self, c: Column) -> str:
        return 'generated by default as identity'

    def drop_statement(self, tbl: TableDef) -> str:
        return f'drop table if exists {self.qname(tbl.name)} cascade'

    def index_statements(self, table_name: QualifiedName, e: Index, opts: Renderer.CreateOptions) -> list[str]:
        if Clustered not in e.options:
            return super().index_statements(table_name, e, opts)

        # A postgres table is a heap, which nothing keeps in any order - not even that of its primary key, so there is
        # no other shape to give it. The most there is to do is to mark the index as the one to cluster on: a `cluster`
        # then puts the table in its order, as of then, and what comes after lands wherever it fits.
        stmts = super().index_statements(
            table_name,
            dc.replace(e, options=tv.TypedValues(*(o for o in e.options if not isinstance(o, Clustered)))),
            opts,
        )
        stmts.append(f'alter table {self.qname(table_name)} cluster on {self.quote_ident(index_name(table_name, e))}')
        return stmts

    def alter_column_statements(self, op: AlterColumn) -> list[str]:
        c = op.column
        nn = 'set' if not c.nullable else 'drop'
        return [
            f'alter table {self.qname(op.table)} alter column {self.quote_ident(c.name)} type {self.column_type(c, is_identity=False)}',  # noqa
            f'alter table {self.qname(op.table)} alter column {self.quote_ident(c.name)} {nn} not null',
        ]
