# ruff: noqa: UP007
import collections.abc
import typing as ta

##


# What js_to_py produces at runtime is None | bool | int | float | str | Object (JS objects, functions, symbols, and
# modules surface as Object handles; null and undefined both surface as None). Statically it is Any, json.loads-style:
# value-returning entry points are a dynamic boundary, and forcing every caller to narrow before indexing would be
# hostile for no safety gain.
type _JsValue = ta.Any

# What py_to_js accepts, checked one level deep. At runtime only dict, list, and tuple convert as containers
# (recursively, with the same value rules) - arbitrary Mapping/Sequence implementations do not - but exact container
# types here would reject legitimate heterogeneous literals through invariance. Buffers become Uint8Arrays, callables
# become JS functions, and Object handles must belong to the target Context.
type _ToJs = ta.Union[
    None,
    bool,
    int,
    float,
    str,
    Object,
    collections.abc.Buffer,
    ta.Callable[..., ta.Any],
    ta.Mapping[str, ta.Any],
    ta.Sequence[ta.Any],
]


##


QJS_VERSION: ta.Final[str]


class JsError(Exception):
    js_stack: str | None


class JsStackOverflowError(JsError): ...


class JsInterruptError(JsError): ...


@ta.final
class Object:
    def invoke(self, name: str, /, *args: _ToJs) -> _JsValue: ...
    def json(self) -> str | None: ...
    def serialize(self) -> bytes: ...
    def keys(self) -> list[str]: ...
    def to_bytes(self) -> bytes: ...
    def promise_state(self) -> ta.Literal['pending', 'fulfilled', 'rejected'] | None: ...
    def promise_result(self) -> _JsValue: ...

    def __call__(self, *args: _ToJs) -> _JsValue: ...
    def __getitem__(self, key: str | int) -> _JsValue: ...
    def __setitem__(self, key: str | int, value: _ToJs) -> None: ...
    def __delitem__(self, key: str | int) -> None: ...


@ta.final
class Context:
    def __init__(self, *, with_std: bool = False, with_bjson: bool = False) -> None: ...

    def eval(
            self,
            code: str,
            *,
            filename: str = '<eval>',
            module: bool = False,
            strict: bool = False,
    ) -> _JsValue: ...

    def get(self, name: str) -> _JsValue: ...
    def set(self, name: str, value: _ToJs) -> None: ...
    def parse_json(self, text: str) -> _JsValue: ...
    def deserialize(self, blob: collections.abc.Buffer) -> _JsValue: ...

    def execute_pending_job(self) -> bool: ...
    def execute_pending_jobs(self) -> int: ...
    def has_pending_jobs(self) -> bool: ...

    def interrupt(self) -> None: ...
    def set_time_limit(self, seconds: float) -> None: ...
    def set_memory_limit(self, limit: int) -> None: ...
    def set_max_stack_size(self, limit: int) -> None: ...
    def set_gc_threshold(self, threshold: int) -> None: ...

    def gc(self) -> None: ...
    def memory(self) -> dict[str, int]: ...

    @property
    def global_this(self) -> Object: ...
