from ....dtypes import STRING
from ....qualifiedname import qn
from ....tabledefs.elements import Column
from ....tabledefs.elements import CreatedAtUpdatedAt
from ....tabledefs.elements import Elements
from ....tabledefs.elements import IdIntegerPrimaryKey
from ....tabledefs.elements import Index
from ....tabledefs.lower import lower_table_elements
from ....tabledefs.rendering import Renderer
from ....tabledefs.tabledefs import TableDef
from ..tabledefs import PostgresTabledefRenderer


def _users(*name):
    return lower_table_elements(TableDef(qn(*name), Elements(
        IdIntegerPrimaryKey(),
        CreatedAtUpdatedAt(),
        Column('name', STRING),
        Index(['name']),
    )))


def test_render_golden():
    assert PostgresTabledefRenderer().render_create_statements(_users('users')) == [
        (
            'create table "users" (\n'
            '  "id" bigint generated by default as identity not null,\n'
            '  "created_at" timestamp with time zone not null default current_timestamp,\n'
            '  "updated_at" timestamp with time zone not null default current_timestamp,\n'
            '  "name" text not null,\n'
            '  primary key ("id")\n'
            ')'
        ),
        'create index "users__index__name" on "users" ("name")\n',
        (
            'create or replace function "users__function__updated_at__updated_at"()\n'
            'returns trigger\n'
            'language plpgsql\n'
            'as $$\n'
            'begin\n'
            '  if new."updated_at" is not distinct from old."updated_at" then\n'
            '    new."updated_at" := current_timestamp;\n'
            '  end if;\n'
            '\n'
            '  return new;\n'
            'end;\n'
            '$$'
        ),
        (
            'create trigger "users__trigger__updated_at__updated_at"\n'
            'before update on "users"\n'
            'for each row\n'
            'execute function "users__function__updated_at__updated_at"()\n'
        ),
    ]


def test_render_qualified_golden():
    stmts = PostgresTabledefRenderer().render_create_statements(
        _users('app', 'users'),
        Renderer.CreateOptions(if_not_exists=True),
    )

    assert stmts[0].startswith('create table if not exists "app"."users" (\n')
    assert stmts[1] == 'create index if not exists "users__index__name" on "app"."users" ("name")\n'
    assert stmts[2].startswith('create or replace function "app"."users__function__updated_at__updated_at"()\n')
    assert stmts[3] == (
        'create or replace trigger "users__trigger__updated_at__updated_at"\n'
        'before update on "app"."users"\n'
        'for each row\n'
        'execute function "app"."users__function__updated_at__updated_at"()\n'
    )
